workflows:
  ios-testflight:
    name: "DanceDate iOS TestFlight Deploy"
    max_build_duration: 120
    environment:
      groups:
        - app_store_credentials # APPSTORE_KEY_ID, APPSTORE_ISSUER_ID, APPSTORE_PRIVATE_KEY
      ios_signing:
        certificates:
          - DD_iOS_AppStore_Distribution2
        provisioning_profiles:
          - DanceDate iOS App Store
    scripts:
      - name: Install dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/DanceDate.xcworkspace" \
            --scheme "DanceDate" \
            --config Release \
            --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APPSTORE_PRIVATE_KEY
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        submit_to_testflight: true
