workflows:
  ios-testflight:
    name: DanceDate iOS TestFlight Deploy
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: DanceDate iOS Production
    environment:
      ios_signing:
        provisioning_profiles:
          - DanceDate iOS App Store
        certificates:
          - DanceDate iOS Distribution
      vars:
        BUNDLE_ID: "com.antho.dancedate"
        XCODE_WORKSPACE: "DanceDate.xcworkspace"
        XCODE_SCHEME: "DanceDate"
      node: 18.20.4
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Set environment overrides for C++17
        script: |
          export GCC_CXX_STANDARD=17
          export CLANG_CXX_LANGUAGE_STANDARD=c++17
          export CXXFLAGS="-std=c++17"
          echo "🔧 Environment variables set to force C++17:"
          echo "GCC_CXX_STANDARD=$GCC_CXX_STANDARD"
          echo "CLANG_CXX_LANGUAGE_STANDARD=$CLANG_CXX_LANGUAGE_STANDARD"
          echo "CXXFLAGS=$CXXFLAGS"

      - name: Install npm dependencies
        script: |
          npm install

      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli

      - name: Create missing assets
        script: |
          mkdir -p assets/sounds
          touch assets/sounds/notification.wav

      - name: Expo prebuild
        script: |
          npx expo prebuild --platform ios --clean

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update

      - name: Clean Xcode DerivedData
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: CI/CD Sanity Nuclear clean of all build artifacts
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          cd ios && rm -rf Pods Podfile.lock build
          rm -rf node_modules
          rm -rf ~/Library/Caches/com.apple.dt.Xcode
          rm -rf ~/Library/Caches/CocoaPods
          npm install

      - name: Patch RNScreens.podspec to hard-code C++17
        script: |
          if [ -f "node_modules/react-native-screens/RNScreens.podspec" ]; then
            echo "🔧 Patching RNScreens.podspec..."
            cp node_modules/react-native-screens/RNScreens.podspec node_modules/react-native-screens/RNScreens.podspec.backup
            cat <<'EOF' >> node_modules/react-native-screens/RNScreens.podspec

  # >>> Codemagic patch to force C++17 <<<
  s.pod_target_xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++17',
    'CLANG_CXX_LIBRARY' => 'libc++'
  }
  # <<< End Codemagic patch >>>
EOF
            echo "✅ C++17 settings appended safely to RNScreens.podspec"
          else
            echo "⚠️ RNScreens.podspec not found"
          fi

      - name: Verify next-level nuke C++17 settings
        script: |
          cd ios
          echo "📦 Checking react-native-screens version:"
          npm list react-native-screens
          if grep -q "NEXT-LEVEL NUKE" Podfile; then
            echo "✅ Next-level nuke settings found in Podfile"
            grep -A 10 "NEXT-LEVEL NUKE" Podfile
          else
            echo "⚠️ Next-level nuke settings not found in Podfile"
          fi

      - name: Install CocoaPods with next-level nuke settings
        script: |
          cd ios
          pod install --repo-update
          echo "🔍 Verifying next-level nuke settings were applied:"
          if grep -q "NEXT-LEVEL NUKE" Podfile; then
            echo "✅ Podfile contains next-level nuke settings"
            grep -A 8 "NEXT-LEVEL NUKE" Podfile
          else
            echo "❌ Podfile missing next-level nuke settings"
          fi
          if [ -f "Pods/Pods.xcodeproj/project.pbxproj" ]; then
            rnscreens_cpp17_count=$(grep -c "RNScreens.*CLANG_CXX_LANGUAGE_STANDARD.*c\+\+17" Pods/Pods.xcodeproj/project.pbxproj || echo "0")
            echo "✅ Found $rnscreens_cpp17_count C++17 settings for RNScreens in Pods project"
            if [ "$rnscreens_cpp17_count" -gt "0" ]; then
              echo "✅ Next-level nuke solution successfully applied to RNScreens"
            else
              echo "⚠️ No C++17 settings found for RNScreens in Pods project"
            fi
          fi

      - name: Create ExportOptions.plist
        script: |
          cd ios
          cat > ExportOptions.plist << "EOF"
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>teamID</key>
              <string>RZ3LX2QC88</string>
          </dict>
          </plist>
          EOF

      - name: Fix iOS deployment targets
        script: |
          cd ios
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' {} \;

      - name: Set up code signing settings on Xcode project
        script: |
          cd ios
          xcode-project use-profiles

      - name: Final clean before archive
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ~/Library/Caches/com.apple.dt.Xcode
          rm -rf ~/Library/Caches/CocoaPods
          echo "🧹 Cleanup complete - no cached build settings should remain"

      - name: Build ipa for distribution
        script: |
          cd ios
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath DanceDate.xcarchive \
            DEVELOPMENT_TEAM=RZ3LX2QC88 \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            COMPILER_INDEX_STORE_ENABLE=NO \
            SWIFT_COMPILATION_MODE=wholemodule \
            SWIFT_OPTIMIZATION_LEVEL=-O \
            CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=NO \
            GCC_WARN_INHIBIT_ALL_WARNINGS=YES \
            CLANG_WARN_DOCUMENTATION_COMMENTS=NO \
            CLANG_WARN_STRICT_PROTOTYPES=NO \
            CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION=NO \
            ONLY_ACTIVE_ARCH=NO

          xcodebuild -exportArchive \
            -archivePath DanceDate.xcarchive \
            -exportPath exports \
            -exportOptionsPlist "$(pwd)/ExportOptions.plist"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
