workflows:
  ios-release:
    name: iOS Release Build
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.antho.dancedate"
        certificates:
          - DD_iOS_AppStore_Distribution2
        provisioning_profiles:
          - DanceDate iOS App Store
      vars:
        XCODE_WORKSPACE: "DanceDate.xcworkspace"
        XCODE_SCHEME: "DanceDate"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx pod-install ios
      - name: Build iOS Release
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/DanceDate.xcarchive \
            archive DEVELOPMENT_TEAM=RZ3LX2QC88 CODE_SIGN_STYLE=Manual
      - name: Export .ipa
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/DanceDate.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/*.dSYM.zip
    publishing:
      app_store_connect:
        api_key: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        private_key: $APPSTORE_PRIVATE_KEY
        submit_to_testflight: true
