workflows:
  ios-testflight:
    name: "DanceDate iOS TestFlight Deploy"
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_credentials # contains APPSTORE_PRIVATE_KEY, APPSTORE_KEY_ID, APPSTORE_ISSUER_ID
      ios_signing:
        certificates:
          - DD_iOS_AppStore_Distribution2
        provisioning_profiles:
          - DanceDate iOS App Store
      vars:
        BUNDLE_ID: "com.antho.dancedate"
        XCODE_WORKSPACE: "DanceDate.xcworkspace"
        XCODE_SCHEME: "DanceDate"
      node: 18.20.4
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Debug Xcode project detection
        script: |
          echo "🔍 Checking available workspaces and schemes..."
          ls ios/*.xcworkspace
          cd ios && xcodebuild -list
      - name: Build iOS IPA
        script: |
          # Let codemagic’s xcode-project use-profiles handle signing + build
          xcode-project use-profiles
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APPSTORE_PRIVATE_KEY
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        submit_to_testflight: true
