workflows:
  ios-testflight:
    name: DanceDate iOS TestFlight Deploy
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: DanceDate iOS Production
    environment:
      ios_signing:
        provisioning_profiles:
          - DanceDate iOS App Store
        certificates:
          - DanceDate iOS Distribution
      vars:
        BUNDLE_ID: "com.antho.dancedate"
        XCODE_WORKSPACE: "DanceDate.xcworkspace"
        XCODE_SCHEME: "DanceDate"
      node: 18.20.4
      xcode: 15.2
      cocoapods: default

    scripts:
      - name: Set environment overrides for C++17
        script: |
          export GCC_CXX_STANDARD=17
          export CLANG_CXX_LANGUAGE_STANDARD=c++17
          export CXXFLAGS="-std=c++17"
          echo "ðŸ”§ Environment variables set to force C++17"

      - name: Install npm dependencies
        script: npm install

      - name: Install Expo CLI
        script: npm install -g @expo/cli

      - name: Create missing assets
        script: |
          mkdir -p assets/sounds
          touch assets/sounds/notification.wav

      - name: Expo prebuild
        script: npx expo prebuild --platform ios --clean

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: CI/CD Sanity Nuclear clean of all build artifacts
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          cd ios && rm -rf Pods Podfile.lock build
          cd ..
          rm -rf node_modules
          rm -rf ~/Library/Caches/com.apple.dt.Xcode
          rm -rf ~/Library/Caches/CocoaPods
          npm install

      - name: Patch RNScreens.podspec to hard-code C++17
        script: |
          if [ -f "node_modules/react-native-screens/RNScreens.podspec" ]; then
            echo "ðŸ”§ Patching RNScreens.podspec..."
            cp node_modules/react-native-screens/RNScreens.podspec node_modules/react-native-screens/RNScreens.podspec.backup
            # Insert C++17 settings into podspec
            sed -i.bak 's/{/{ "CLANG_CXX_LANGUAGE_STANDARD" => "c++17", "CLANG_CXX_LIBRARY" => "libc++",/' node_modules/react-native-screens/RNScreens.podspec
            grep "CLANG_CXX_LANGUAGE_STANDARD" node_modules/react-native-screens/RNScreens.podspec || echo "âš ï¸ Patch failed"
          else
            echo "âš ï¸ RNScreens.podspec not found"
          fi

      - name: Install CocoaPods with patched podspec
        script: |
          cd ios
          pod install --repo-update

      - name: Create ExportOptions.plist
        script: |
          cd ios
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>teamID</key>
              <string>RZ3LX2QC88</string>
          </dict>
          </plist>
          EOF

      - name: Fix iOS deployment targets
        script: |
          cd ios
          find . -name "*.pbxproj" -exec sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/' {} \;

      - name: Set up code signing settings on Xcode project
        script: |
          cd ios
          xcode-project use-profiles

      - name: Build ipa for distribution
        script: |
          cd ios
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath DanceDate.xcarchive \
            DEVELOPMENT_TEAM=RZ3LX2QC88 \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            COMPILER_INDEX_STORE_ENABLE=NO
          xcodebuild -exportArchive \
            -archivePath DanceDate.xcarchive \
            -exportPath exports \
            -exportOptionsPlist "$(pwd)/ExportOptions.plist"

    artifacts:
      - ios/exports/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
