workflows:
  ios-testflight:
    name: DanceDate iOS TestFlight Deploy
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: DanceDate iOS Production
    environment:
      ios_signing:
        provisioning_profiles:
          - DanceDate iOS App Store
        certificates:
          - DanceDate iOS Distribution
      vars:
        BUNDLE_ID: "com.antho.dancedate"
        XCODE_WORKSPACE: "DanceDate.xcworkspace"
        XCODE_SCHEME: "DanceDate"
      node: 18.17.0
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Create missing assets
        script: |
          mkdir -p assets/sounds
          touch assets/sounds/notification.wav
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform ios --clean
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Create minimal React Native build
        script: |
          cd ios
          # Create a minimal React Native build without Expo
          echo "Creating minimal React Native build to test pipeline..."
          
          # Remove all Expo dependencies and create minimal package.json
          cd ..
          cat > package.json << 'EOF'
          {
            "name": "dancedate-ios",
            "version": "1.0.3",
            "private": true,
            "scripts": {
              "start": "react-native start",
              "ios": "react-native run-ios",
              "android": "react-native run-android"
            },
            "dependencies": {
              "react": "19.0.0",
              "react-native": "0.79.5"
            },
            "devDependencies": {
              "@babel/core": "^7.25.2",
              "@babel/preset-env": "^7.25.2",
              "@babel/runtime": "^7.25.2",
              "babel-jest": "^29.7.0",
              "jest": "^29.7.0",
              "metro-react-native-babel-preset": "0.77.0",
              "react-test-renderer": "19.0.0"
            },
            "jest": {
              "preset": "react-native"
            }
          }
          EOF
          
          # Clean and reinstall
          rm -rf node_modules
          npm install
          
          cd ios
          # Clean and reinstall pods
          rm -rf Pods
          rm Podfile.lock
          pod install --repo-update
      - name: Fix iOS deployment targets
        script: |
          cd ios
          # Fix deployment target warnings by setting minimum iOS version
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' {} \;
      - name: Set up code signing settings on Xcode project
        script: |
          cd ios
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          cd ios
          # Clean build folder first
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release
          
          # Build archive with automatic code signing and compilation fixes
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath DanceDate.xcarchive \
            DEVELOPMENT_TEAM=RZ3LX2QC88 \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            COMPILER_INDEX_STORE_ENABLE=NO \
            SWIFT_COMPILATION_MODE=wholemodule \
            SWIFT_OPTIMIZATION_LEVEL=-O \
            CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=NO \
            GCC_WARN_INHIBIT_ALL_WARNINGS=YES \
            CLANG_WARN_DOCUMENTATION_COMMENTS=NO \
            CLANG_WARN_STRICT_PROTOTYPES=NO \
            CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION=NO \
            ONLY_ACTIVE_ARCH=NO
          
          # Export IPA with absolute path to ExportOptions.plist
          xcodebuild -exportArchive \
            -archivePath DanceDate.xcarchive \
            -exportPath exports \
            -exportOptionsPlist "$(pwd)/ExportOptions.plist"
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
