workflows:
  ios-testflight:
    name: DanceDate iOS TestFlight Deploy
    environment:
      groups:
        - app_store_connect
      ios_signing:
        certificates:
          - DD_iOS_AppStore_Distribution2
        provisioning_profiles:
          - DanceDate iOS App Store
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install --repo-update && cd ..
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/DanceDate.xcworkspace" \
            --scheme "DanceDate" \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APPSTORE_PRIVATE_KEY
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
