name: Production Build and Deploy to TestFlight

on:
  workflow_dispatch:

jobs:
  production-deploy:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Expo CLI
        run: npm install -g @expo/cli
        
      - name: Create missing assets
        run: |
          mkdir -p assets/sounds
          touch assets/sounds/notification.wav
          
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          
      - name: Verify Certificates
        run: |
          echo "🔐 Available code signing identities:"
          security find-identity -v -p codesigning
          
      - name: Expo prebuild for Production
        run: npx expo prebuild --platform ios --clean
        
      - name: Fix iOS Deployment Target
        run: |
          cd ios
          echo "🔧 Fixing deployment targets for production..."
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 9.0/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' {} \;
          echo "✅ Deployment targets updated"
          
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
          
      - name: Build Archive for App Store
        run: |
          cd ios
          echo "🏗️ Building archive for App Store distribution..."
          xcodebuild archive \
            -workspace DanceDate.xcworkspace \
            -scheme DanceDate \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath DanceDate.xcarchive \
            DEVELOPMENT_TEAM=RZ3LX2QC88 \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates
            
      - name: Export IPA for App Store
        run: |
          cd ios
          echo "📦 Exporting IPA for App Store submission..."
          xcodebuild -exportArchive \
            -archivePath DanceDate.xcarchive \
            -exportPath exports \
            -exportOptionsPlist ExportOptions.plist
            
      - name: Verify IPA Creation
        run: |
          cd ios
          echo "📱 Checking for IPA file..."
          ls -la exports/
          IPA_FILE=$(find exports -name "*.ipa" -type f | head -1)
          echo "✅ IPA found: $IPA_FILE"
          
      - name: Upload to TestFlight
        run: |
          cd ios
          echo "🚀 Uploading to TestFlight..."
          IPA_FILE=$(find exports -name "*.ipa" -type f | head -1)
          
          xcrun altool --upload-app \
            --type ios \
            --file "$IPA_FILE" \
            --apiKey Q7GZ89252A \
            --apiIssuer dc671579-38b9-4e57-91dd-41ad841eeed6 \
            --verbose
            
      - name: Success
        run: |
          echo "🎉 Production build v1.0.3 (12) uploaded to TestFlight!"
          echo "📱 Check App Store Connect in 5-10 minutes"
          echo "💰 FREE production deployment complete!"
