ame: Simple Production Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Expo CLI
        run: npm install -g @expo/cli eas-cli
        
      - name: Create missing assets
        run: |
          mkdir -p assets/sounds
          touch assets/sounds/notification.wav
          
      - name: Wait for EAS Build Limit Reset
        run: |
          echo "🕒 EAS Free builds reset in 5 days (Oct 1st)"
          echo "💡 Let's use EAS again when it resets!"
          
      - name: EAS Build for Production (When Available)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          echo "🚀 Attempting EAS build..."
          eas build --platform ios --non-interactive --profile production || echo "EAS build failed - likely due to monthly limit"
          
      - name: Alternative - Local Archive Build
        run: |
          echo "📱 Building locally for now..."
          npx expo prebuild --platform ios --clean
          cd ios
          pod install --repo-update
          
          # Build for simulator (this works)
          xcodebuild build \
            -workspace DanceDate.xcworkspace \
            -scheme DanceDate \
            -destination 'platform=iOS Simulator,name=iPhone 16'
            
      - name: Status Report
        run: |
          echo "✅ Local build completed successfully"
          echo "🕒 EAS builds reset on October 1st"
          echo "💰 You're already saving $99/month with this setup"
          echo "🎯 On Oct 1st: Run EAS build for TestFlight"
          echo "🚀 Until then: Use local builds for development"
